---
- hosts: localhost
  tasks:
    - name: Wait for bastion available via nlb
      wait_for:
        port: 22
        host: "{{ item }}.{{ dns_domain }}"
        search_regex: OpenSSH
        delay: 6
      connection: local
      when: state is defined and state == "present"
      loop: "{{ env_names.split('\n') }}"

- hosts: bastion
  tasks:
    - name: Configure Bastion
      import_role:
        name: tigera.internal.lynx_bastion
      when: state is defined and state == "present"

- hosts: control:worker
  tasks:
    - debug: msg="{{ hostvars[groups['bastion'] | intersect(groups[key_name]) | first][key_name + '_bastion_ssh_key'] }}"

    - name: Authorize bastion ssh key
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ hostvars[groups['bastion'] | intersect(groups[key_name]) | first][key_name + '_bastion_ssh_key'] }}"
      when: state is defined and state == "present"

    - name: Install docker
      import_role:
        name: tigera.internal.docker
      when: state is defined and state == "present"

    - name: Install kubeadm
      import_role:
        name: tigera.internal.kubeadm
      when: state is defined and state == "present"

- hosts: control
  tasks:
    - name: Set join token fact
      set_fact:
        join_token: "{{ env_names | md5 }}"
# TODO: Fix the above

    - name: kubeadm init on first control node
      import_role:
        name: tigera.internal.kubeadm
        tasks_from: init.yaml
      when: state is defined and state == "present"

- hosts: worker
  tasks:
    - name: Set join token fact
      set_fact:
        join_token: "{{ env_names | md5 }}"
# TODO: Fix the above

    - name: kubeadm join worker node
      import_role:
        name: tigera.internal.kubeadm
        tasks_from: join.yaml
      when: state is defined and state == "present"

- hosts: bastion
  tasks:
    - name: Configure kubeconfig on bastion
      import_role:
        name: tigera.internal.kubeadm
        tasks_from: kubeconfig.yaml
      when: state is defined and state == "present"
